[data]
image_dims = 224

[turbulent_delay]
output_path = '/home/conradb/git/insar-syn-gen/ifg_outputs/turbulent_atm_noise/'
rescale = 500 # rescale size
pixel_size_x = 1
pixel_size_y = 1
rows = 100
cols = 100
samples = 20000
wrapped = true
maxcovs = [5.5, 6.5, 7.5, 8.25, 9.0] # from https://github.com/pui-nantheera/Synthetic_InSAR_image/blob/da224d217ae95d0198d4b8514b96b8f0328ca1b9/main_code/runGenTurbulent.m#L25C5-L25C36
alphas = [0.004, 0.006, 0.008, 0.012, 0.016] # from https://github.com/pui-nantheera/Synthetic_InSAR_image/blob/da224d217ae95d0198d4b8514b96b8f0328ca1b9/main_code/runGenTurbulent.m#L26C17-L26C41

[stratified]
output_path = '/home/conradb/git/insar-syn-gen/ifg_outputs/stratified_atm_noise/'
rescale = 500
samples = 500
incidence = 43.7835
wrapped = true

[deformation]
max_dist = 25000 # pre crop +/- max dist in metres from source
pixel_size = 100 # pre crop pixel spacing in metres, image will have size max_dist * 2 / pixel_size e.g. 25000*2 / 100 = 500x500 pixels
source = 4
volumes = [5.0, 5.2, 5.5, 5.7, 6.2, 6.3, 6.4, 6.5, 6.7, 6.9, 7.2, 7.4, 7.7, 7.8]
headings = [5, 45, 85, 125, 165, 205, 245, 285, 325]
incidences = [29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 45, 46]
crop = 224
output_path = '/home/conradb/git/insar-syn-gen/ifg_outputs/deformation/'
min_def_range = 10 # minimum value of deformation in mm to ensure min-max range is within a limit to prevent wrapping discontinuities
max_def_range = 60 # max value of deformation in mm to ensure min-max range is within a limit to prevent wrapping discontinuities
max_samples = 10000
wrapped = true

[combine]
samples = 2000
root_dir = '/home/conradb/git/insar-syn-gen/ifg_outputs/'
